// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpd3Y1NtDlFFuDxukn6h5RGN2-Z8VT1-M',
    appId: '1:47322250236:web:d3e3952d510fcd84bb1079',
    messagingSenderId: '47322250236',
    projectId: 'clone-8479d',
    authDomain: 'clone-8479d.firebaseapp.com',
    storageBucket: 'clone-8479d.firebasestorage.app',
    measurementId: 'G-KTFHSB3Q2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAks-TXtAOMhYsgpLmbCAJvYVMc1WpKVhQ',
    appId: '1:47322250236:android:a015ec71b23e0eadbb1079',
    messagingSenderId: '47322250236',
    projectId: 'clone-8479d',
    storageBucket: 'clone-8479d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdIPwTU6r39JS0VfwV6F6YhIeJQKgrag8',
    appId: '1:47322250236:ios:b72bd39304d3517fbb1079',
    messagingSenderId: '47322250236',
    projectId: 'clone-8479d',
    storageBucket: 'clone-8479d.firebasestorage.app',
    androidClientId: '47322250236-dkcu8ikn82fp993kegaijd7ae41b21nd.apps.googleusercontent.com',
    iosClientId: '47322250236-v7smdldj76qdlcb4p3orjqdlmn6kd8v8.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdIPwTU6r39JS0VfwV6F6YhIeJQKgrag8',
    appId: '1:47322250236:ios:b1d6a5b10b57d3ddbb1079',
    messagingSenderId: '47322250236',
    projectId: 'clone-8479d',
    storageBucket: 'clone-8479d.firebasestorage.app',
    androidClientId: '47322250236-dkcu8ikn82fp993kegaijd7ae41b21nd.apps.googleusercontent.com',
    iosClientId: '47322250236-ll4ehv8r5dshpoa79itpkrghrv1mrs6e.apps.googleusercontent.com',
    iosBundleId: 'com.example.myap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpd3Y1NtDlFFuDxukn6h5RGN2-Z8VT1-M',
    appId: '1:47322250236:web:a4a3fe635b1ec682bb1079',
    messagingSenderId: '47322250236',
    projectId: 'clone-8479d',
    authDomain: 'clone-8479d.firebaseapp.com',
    storageBucket: 'clone-8479d.firebasestorage.app',
    measurementId: 'G-21G8QTC2ET',
  );
}
